### ISSUE TITLE
package install failed

### ISSUE THREAD

**Issue by atyre2** [TrashBirdEcology/regimeDetectionMeasures#1]
On installation from github via devtools::install_github() I got this message
```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘regimeDetectionMeasures’ in namespaceExport(ns, exports):
 undefined exports: interpolate_FI_VI, interpolate_distance
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/regimeDetectionMeasures’
Installation failed: Command failed (1)
```

**Comment by TrashBirdEcology** [comment]
@atyre2 which functions are you asking about?

**Comment by TrashBirdEcology** [comment]
> I searched for those functions but they aren't part of the package AFAICS?
 Which functions?


> Another suggestion -- use issues for TODO list. More tools.

Thanks, I will do that.

**Comment by atyre2** [comment]
Listed in error message after "undefined exports":
undefined exports: interpolate_FI_VI, interpolate_distance

**Comment by TrashBirdEcology** [comment]
Solved: documents needed to be updated .

**Comment by TrashBirdEcology** [comment]
Solved: documents needed to be updated.
